---
abstract: "add an \"x_contributors\" section to your META.yml"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::Contributors
name: Module-Install-Contributors
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Install: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Module-Install-Contributors
  homepage: https://metacpan.org/release/Module-Install-Contributors
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-module-install-contributors
version: 0.001
x_contributors:
  - 'Alan Smithee'
  - 'Nicolas Bourbaki'
  - Spartacus
